name: "Sync Apps List"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-files:
    name: "Run sync"
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.commit_message.outputs.message }}
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v6

      - name: "Get commit message"
        id: commit_message
        run: |
          COMMIT_MESSAGE="Update list of obsoleted and archived apps/repositories"
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: "Run test"
        run: |
          chmod a+x ./test.sh
          ./test.sh

      - name: "Push to Source"
        run: |
          git config --global user.name "web-flow"
          git config --global user.email "noreply@github.com"
          git add archived-apps obsolete-apps
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "${{ steps.commit_message.outputs.message }}"
            git push && echo "Sync to Source succeeded" >> $GITHUB_STEP_SUMMARY
          fi
